required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: -277.5
  y: 64
  z: 2.5
  yaw: 90
  pitch: 0
arenas:
  0:
    player-spawn:
      world: 'world'
      x: -290.5
      y: 64
      z: 6.5
      yaw: 55
      pitch: 0
    sign:
      world: 'world'
      x: -278
      y: 65
      z: 6
  1:
    player-spawn:
      world: 'world'
      x: -290.5
      y: 64
      z: -3.5
      yaw: 55
      pitch: 0
    sign:
      world: 'world'
      x: -279
      y: 65
      z: